# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/datasource_setup_sardana.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SardanaSetup(object):
    def setupUi(self, SardanaSetup):
        SardanaSetup.setObjectName("SardanaSetup")
        SardanaSetup.resize(640, 726)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SardanaSetup)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gb_door = QtWidgets.QFrame(SardanaSetup)
        self.gb_door.setObjectName("gb_door")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gb_door)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lb_door_address = QtWidgets.QLabel(self.gb_door)
        self.lb_door_address.setObjectName("lb_door_address")
        self.gridLayout_2.addWidget(self.lb_door_address, 0, 0, 1, 1)
        self.le_door_address = QtWidgets.QLineEdit(self.gb_door)
        self.le_door_address.setObjectName("le_door_address")
        self.gridLayout_2.addWidget(self.le_door_address, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.gb_door)
        self.line_3 = QtWidgets.QFrame(SardanaSetup)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label = QtWidgets.QLabel(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.rb_mask_off = QtWidgets.QRadioButton(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_mask_off.setFont(font)
        self.rb_mask_off.setChecked(True)
        self.rb_mask_off.setObjectName("rb_mask_off")
        self.bg_mask_option = QtWidgets.QButtonGroup(SardanaSetup)
        self.bg_mask_option.setObjectName("bg_mask_option")
        self.bg_mask_option.addButton(self.rb_mask_off)
        self.verticalLayout.addWidget(self.rb_mask_off)
        self.rb_mask_on = QtWidgets.QRadioButton(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_mask_on.setFont(font)
        self.rb_mask_on.setObjectName("rb_mask_on")
        self.bg_mask_option.addButton(self.rb_mask_on)
        self.verticalLayout.addWidget(self.rb_mask_on)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_mask_file = QtWidgets.QLabel(SardanaSetup)
        self.lb_mask_file.setMinimumSize(QtCore.QSize(200, 0))
        self.lb_mask_file.setText("")
        self.lb_mask_file.setObjectName("lb_mask_file")
        self.horizontalLayout_2.addWidget(self.lb_mask_file)
        self.but_load_mask = QtWidgets.QPushButton(SardanaSetup)
        self.but_load_mask.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_load_mask.setFont(font)
        self.but_load_mask.setObjectName("but_load_mask")
        self.horizontalLayout_2.addWidget(self.but_load_mask)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_5 = QtWidgets.QFrame(SardanaSetup)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.label_9 = QtWidgets.QLabel(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.rb_fill_off = QtWidgets.QRadioButton(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_fill_off.setFont(font)
        self.rb_fill_off.setChecked(True)
        self.rb_fill_off.setObjectName("rb_fill_off")
        self.bg_fill_option = QtWidgets.QButtonGroup(SardanaSetup)
        self.bg_fill_option.setObjectName("bg_fill_option")
        self.bg_fill_option.addButton(self.rb_fill_off)
        self.verticalLayout.addWidget(self.rb_fill_off)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.rb_fill_on = QtWidgets.QRadioButton(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_fill_on.setFont(font)
        self.rb_fill_on.setObjectName("rb_fill_on")
        self.bg_fill_option.addButton(self.rb_fill_on)
        self.horizontalLayout_9.addWidget(self.rb_fill_on)
        self.label_10 = QtWidgets.QLabel(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.sb_fill = QtWidgets.QSpinBox(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sb_fill.setFont(font)
        self.sb_fill.setObjectName("sb_fill")
        self.horizontalLayout_9.addWidget(self.sb_fill)
        self.label_11 = QtWidgets.QLabel(SardanaSetup)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.line = QtWidgets.QFrame(SardanaSetup)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_6 = QtWidgets.QLabel(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.rb_ff_off = QtWidgets.QRadioButton(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_ff_off.setFont(font)
        self.rb_ff_off.setChecked(True)
        self.rb_ff_off.setObjectName("rb_ff_off")
        self.bg_ff_option = QtWidgets.QButtonGroup(SardanaSetup)
        self.bg_ff_option.setObjectName("bg_ff_option")
        self.bg_ff_option.addButton(self.rb_ff_off)
        self.verticalLayout.addWidget(self.rb_ff_off)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rb_ff_on = QtWidgets.QRadioButton(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_ff_on.setFont(font)
        self.rb_ff_on.setObjectName("rb_ff_on")
        self.bg_ff_option.addButton(self.rb_ff_on)
        self.horizontalLayout_8.addWidget(self.rb_ff_on)
        self.label_7 = QtWidgets.QLabel(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.dsb_ff_from = QtWidgets.QDoubleSpinBox(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dsb_ff_from.setFont(font)
        self.dsb_ff_from.setObjectName("dsb_ff_from")
        self.horizontalLayout_8.addWidget(self.dsb_ff_from)
        self.label_8 = QtWidgets.QLabel(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.dsb_ff_to = QtWidgets.QDoubleSpinBox(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dsb_ff_to.setFont(font)
        self.dsb_ff_to.setObjectName("dsb_ff_to")
        self.horizontalLayout_8.addWidget(self.dsb_ff_to)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lb_ff_file = QtWidgets.QLabel(SardanaSetup)
        self.lb_ff_file.setMinimumSize(QtCore.QSize(200, 0))
        self.lb_ff_file.setText("")
        self.lb_ff_file.setObjectName("lb_ff_file")
        self.horizontalLayout_5.addWidget(self.lb_ff_file)
        self.but_load_ff = QtWidgets.QPushButton(SardanaSetup)
        self.but_load_ff.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_load_ff.setFont(font)
        self.but_load_ff.setObjectName("but_load_ff")
        self.horizontalLayout_5.addWidget(self.but_load_ff)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line_4 = QtWidgets.QFrame(SardanaSetup)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.label_2 = QtWidgets.QLabel(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.rb_inten_off = QtWidgets.QRadioButton(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_inten_off.setFont(font)
        self.rb_inten_off.setChecked(True)
        self.rb_inten_off.setObjectName("rb_inten_off")
        self.bg_intensity = QtWidgets.QButtonGroup(SardanaSetup)
        self.bg_intensity.setObjectName("bg_intensity")
        self.bg_intensity.addButton(self.rb_inten_off)
        self.verticalLayout.addWidget(self.rb_inten_off)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rb_inten_on = QtWidgets.QRadioButton(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_inten_on.setFont(font)
        self.rb_inten_on.setObjectName("rb_inten_on")
        self.bg_intensity.addButton(self.rb_inten_on)
        self.horizontalLayout_3.addWidget(self.rb_inten_on)
        self.cmb_intensity = QtWidgets.QComboBox(SardanaSetup)
        self.cmb_intensity.setEnabled(False)
        self.cmb_intensity.setObjectName("cmb_intensity")
        self.horizontalLayout_3.addWidget(self.cmb_intensity)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(SardanaSetup)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_4 = QtWidgets.QLabel(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.rb_atten_off = QtWidgets.QRadioButton(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_atten_off.setFont(font)
        self.rb_atten_off.setChecked(True)
        self.rb_atten_off.setObjectName("rb_atten_off")
        self.bg_attenuator = QtWidgets.QButtonGroup(SardanaSetup)
        self.bg_attenuator.setObjectName("bg_attenuator")
        self.bg_attenuator.addButton(self.rb_atten_off)
        self.verticalLayout.addWidget(self.rb_atten_off)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.rb_atten_on = QtWidgets.QRadioButton(SardanaSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_atten_on.setFont(font)
        self.rb_atten_on.setObjectName("rb_atten_on")
        self.bg_attenuator.addButton(self.rb_atten_on)
        self.horizontalLayout_6.addWidget(self.rb_atten_on)
        self.cmb_attenuator = QtWidgets.QComboBox(SardanaSetup)
        self.cmb_attenuator.setEnabled(False)
        self.cmb_attenuator.setObjectName("cmb_attenuator")
        self.horizontalLayout_6.addWidget(self.cmb_attenuator)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gv_main = GraphicsView(SardanaSetup)
        self.gv_main.setAutoFillBackground(False)
        self.gv_main.setStyleSheet("")
        self.gv_main.setObjectName("gv_main")
        self.horizontalLayout.addWidget(self.gv_main)

        self.retranslateUi(SardanaSetup)
        QtCore.QMetaObject.connectSlotsByName(SardanaSetup)

    def retranslateUi(self, SardanaSetup):
        _translate = QtCore.QCoreApplication.translate
        SardanaSetup.setWindowTitle(_translate("SardanaSetup", "Form"))
        self.label_3.setText(_translate("SardanaSetup", "Door monitor"))
        self.lb_door_address.setText(_translate("SardanaSetup", "Address:"))
        self.label.setText(_translate("SardanaSetup", "Mask corection:"))
        self.rb_mask_off.setText(_translate("SardanaSetup", "OFF"))
        self.rb_mask_on.setText(_translate("SardanaSetup", "ON"))
        self.but_load_mask.setText(_translate("SardanaSetup", "Load new"))
        self.label_9.setText(_translate("SardanaSetup", "Mask gaps fill:"))
        self.rb_fill_off.setText(_translate("SardanaSetup", "OFF"))
        self.rb_fill_on.setText(_translate("SardanaSetup", "ON"))
        self.label_10.setText(_translate("SardanaSetup", "radius:"))
        self.label_11.setText(_translate("SardanaSetup", "px."))
        self.label_6.setText(_translate("SardanaSetup", "Flat field correction:"))
        self.rb_ff_off.setText(_translate("SardanaSetup", "OFF"))
        self.rb_ff_on.setText(_translate("SardanaSetup", "ON"))
        self.label_7.setText(_translate("SardanaSetup", "from"))
        self.label_8.setText(_translate("SardanaSetup", "to"))
        self.but_load_ff.setText(_translate("SardanaSetup", "Load new"))
        self.label_2.setText(_translate("SardanaSetup", "Intensity correction:"))
        self.rb_inten_off.setText(_translate("SardanaSetup", "OFF"))
        self.rb_inten_on.setText(_translate("SardanaSetup", "ON"))
        self.label_4.setText(_translate("SardanaSetup", "Attenuator correction:"))
        self.rb_atten_off.setText(_translate("SardanaSetup", "OFF"))
        self.rb_atten_on.setText(_translate("SardanaSetup", "ON"))

from pyqtgraph import GraphicsView
