# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/frame_view.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FrameView(object):
    def setupUi(self, FrameView):
        FrameView.setObjectName("FrameView")
        FrameView.resize(748, 421)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(FrameView)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.v_layout = QtWidgets.QVBoxLayout()
        self.v_layout.setObjectName("v_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.view_widget = QtWidgets.QWidget(FrameView)
        self.view_widget.setObjectName("view_widget")
        self.view_layout = QtWidgets.QHBoxLayout(self.view_widget)
        self.view_layout.setObjectName("view_layout")
        self.horizontalLayout.addWidget(self.view_widget)
        self.fr_hist = QtWidgets.QFrame(FrameView)
        self.fr_hist.setMinimumSize(QtCore.QSize(150, 0))
        self.fr_hist.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fr_hist.setObjectName("fr_hist")
        self.hist_layout = QtWidgets.QVBoxLayout(self.fr_hist)
        self.hist_layout.setObjectName("hist_layout")
        self.label = QtWidgets.QLabel(self.fr_hist)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.hist_layout.addWidget(self.label)
        self.line_3 = QtWidgets.QFrame(self.fr_hist)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.hist_layout.addWidget(self.line_3)
        self.rb_hist_selected = QtWidgets.QRadioButton(self.fr_hist)
        self.rb_hist_selected.setChecked(True)
        self.rb_hist_selected.setObjectName("rb_hist_selected")
        self.bg_hist_selection = QtWidgets.QButtonGroup(FrameView)
        self.bg_hist_selection.setObjectName("bg_hist_selection")
        self.bg_hist_selection.addButton(self.rb_hist_selected)
        self.hist_layout.addWidget(self.rb_hist_selected)
        self.rb_hist_all = QtWidgets.QRadioButton(self.fr_hist)
        self.rb_hist_all.setObjectName("rb_hist_all")
        self.bg_hist_selection.addButton(self.rb_hist_all)
        self.hist_layout.addWidget(self.rb_hist_all)
        self.line_2 = QtWidgets.QFrame(self.fr_hist)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.hist_layout.addWidget(self.line_2)
        self.rb_lin_levels = QtWidgets.QRadioButton(self.fr_hist)
        self.rb_lin_levels.setChecked(True)
        self.rb_lin_levels.setObjectName("rb_lin_levels")
        self.bg_lev_mode = QtWidgets.QButtonGroup(FrameView)
        self.bg_lev_mode.setObjectName("bg_lev_mode")
        self.bg_lev_mode.addButton(self.rb_lin_levels)
        self.hist_layout.addWidget(self.rb_lin_levels)
        self.rb_log_levels = QtWidgets.QRadioButton(self.fr_hist)
        self.rb_log_levels.setObjectName("rb_log_levels")
        self.bg_lev_mode.addButton(self.rb_log_levels)
        self.hist_layout.addWidget(self.rb_log_levels)
        self.rb_sqrt_levels = QtWidgets.QRadioButton(self.fr_hist)
        self.rb_sqrt_levels.setObjectName("rb_sqrt_levels")
        self.bg_lev_mode.addButton(self.rb_sqrt_levels)
        self.hist_layout.addWidget(self.rb_sqrt_levels)
        self.line = QtWidgets.QFrame(self.fr_hist)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hist_layout.addWidget(self.line)
        self.chk_auto_levels = QtWidgets.QCheckBox(self.fr_hist)
        self.chk_auto_levels.setChecked(True)
        self.chk_auto_levels.setObjectName("chk_auto_levels")
        self.hist_layout.addWidget(self.chk_auto_levels)
        self.hist = HistogramLUTWidget(self.fr_hist)
        self.hist.setObjectName("hist")
        self.hist_layout.addWidget(self.hist)
        self.hist_layout.setStretch(10, 1)
        self.horizontalLayout.addWidget(self.fr_hist)
        self.horizontalLayout.setStretch(0, 1)
        self.v_layout.addLayout(self.horizontalLayout)
        self.cut_selectors = CutSelector(FrameView)
        self.cut_selectors.setMinimumSize(QtCore.QSize(330, 0))
        self.cut_selectors.setObjectName("cut_selectors")
        self.v_layout.addWidget(self.cut_selectors)
        self.v_layout.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.v_layout)

        self.retranslateUi(FrameView)
        QtCore.QMetaObject.connectSlotsByName(FrameView)

    def retranslateUi(self, FrameView):
        _translate = QtCore.QCoreApplication.translate
        FrameView.setWindowTitle(_translate("FrameView", "Form"))
        self.label.setText(_translate("FrameView", "Levels"))
        self.rb_hist_selected.setText(_translate("FrameView", "Selection"))
        self.rb_hist_all.setText(_translate("FrameView", "All frames"))
        self.rb_lin_levels.setText(_translate("FrameView", "Lin"))
        self.rb_log_levels.setText(_translate("FrameView", "Log"))
        self.rb_sqrt_levels.setText(_translate("FrameView", "Sqrt"))
        self.chk_auto_levels.setText(_translate("FrameView", "Auto"))

from petra_viewer.widgets.cut_selector import CutSelector
from pyqtgraph import HistogramLUTWidget
import petra_viewer.gui.icons_rc
